service: orchestrator-final-lex-bot-v1
frameworkVersion: '3'

useDotenv: true

provider:
  name   : aws
  region : us-east-1 
  runtime: python3.9

  iam:
    role:
      name: role-orchestrator-for-sprint-final
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:GetObjectAttributes
            - lex:RecognizeText
          Resource: "*"

  environment:
    TWILIO_WHATS_FROM: ${env:TWILIO_WHATS_FROM}
    TWILIO_WHATS_TO: ${env:TWILIO_WHATS_TO}
    TWILIO_ID: ${env:TWILIO_ID}
    TWILIO_TOKEN: ${env:TWILIO_TOKEN}
    BUCKET_NAME: ${env:BUCKET_NAME}
    START_CONVERSATION_MESSAGE: ${env:START_CONVERSATION_MESSAGE}
    BOT_ID: ${env:BOT_ID}
    BOT_ALIAS: ${env:BOT_ALIAS}
    BOT_ARN: ${env:BOT_ARN}

functions:
  twilio2:
    handler: controllers/new_func_twilio.new_func_twilio
    events:
      - httpApi:
          path: /twilio-integration
          method: post
  orchestrator:
    handler: controllers/orchestrator.orchestrator_handler
    events:
      - httpApi:
          path: /orchestrator
          method: post
          
plugins:
  - serverless-offline
  - serverless-python-requirements