service: final-lex-bot-v1
frameworkVersion: '3'

useDotenv: true

provider:
  name   : aws
  region : us-east-1 
  runtime: python3.9
  timeout: 120

  iam:
    role:
      name: role-for-sprint-final
      statements:
        - Effect: Allow
          Action:
            - rekognition:DetectText
            - "polly:SynthesizeSpeech"
            - s3:GetObject
            - s3:PutObject
            - s3:GetObjectAttributes
            - translate:TranslateText
            - transcribe:StartTranscriptionJob
            - transcribe:GetTranscriptionJob
          Resource: "*"
        - Effect: Allow
          Action: lambda:InvokeFunction
          Resource: "*"

  environment:
    API_KEY_OPENCAGE_GEOCODE: ${env:API_KEY_OPENCAGE_GEOCODE}
    AROUND_SEARCH_PLACES: ${env:AROUND_SEARCH_PLACES}
    NUMBER_OF_PLACES: ${env:NUMBER_OF_PLACES}
    VIA_CEP_BASE_URL: ${env:VIA_CEP_BASE_URL}
    OVERPASS_API_BASE_URL: ${env:OVERPASS_API_BASE_URL}
    OPENSTREETMAP_BASE_URL: ${env:OPENSTREETMAP_BASE_URL}
    BUCKET_NAME: ${env:BUCKET_NAME}
    IMAGE_NAME: ${env:IMAGE_NAME}

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:BUCKET_NAME}
        PublicAccessBlockConfiguration:
          BlockPublicPolicy: false
          RestrictPublicBuckets: false
    MyBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
          Bucket:
            Ref: S3Bucket
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Principal:
                  AWS: "*"
                Action: 
                  - s3:GetObject
                  - s3:GetObjectAttributes
                  - s3:PutObject
                Resource:
                  Fn::Join:
                    - ""
                    - - "arn:aws:s3:::"
                      - Ref: S3Bucket
                      - "/*"
              - Effect: Allow
                Principal:
                  AWS: "arn:aws:iam::${aws:accountId}:role/${self:provider.iam.role.name}"
                Action: 
                  - s3:ListBucket
                Resource:
                  Fn::Join:
                    - ""
                    - - "arn:aws:s3:::"
                      - Ref: S3Bucket

functions:
  lexIntentVerifier:
    handler: router_controller.handlerLexIntentVerifier

  image_to_text:
    handler: controllers/intents/image_text_extraction_controller.handle_image_to_text

  text_audio_translater:
    handler: controllers/intents/text_audio_translater_controller.handle_text_audio_translater

  cep_to_places:
    handler: controllers/intents/cep_to_places_controller.handle_cep_to_places

  emergency_contacts:
    handler: controllers/intents/emergency_contacts_controller.handle_emergency_contacts

  how_to_make_docs:
    handler: controllers/intents/how_to_make_docs_controller.handle_how_to_make_docs

plugins:
  - serverless-offline
  - serverless-python-requirements