service: uffs-bot-backend

useDotenv: true

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1 
  environment:
    SNS_TOPIC_ARN: ${ssm:uffs-bot-developers-topic-arn}
    ContactUsIntent: ${env:ContactUsIntent}
    LEX_BOT_ID: ${env:BOT_ID}
    LEX_ALIAS_ID: ${env:BOT_ALIAS_ID}
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    CC_API_BASE_URL: ${env:CC_API_BASE_URL}
    SIGN_IN_LAMBDA: ${env:SIGN_IN_LAMBDA}
  iam:
    role:
      name: role-for-middleware-lambda-lex-bot
      statements:
        - Effect: Allow
          Action: lambda:InvokeFunction
          Resource: "*"
        - Effect: Allow
          Action: sns:Publish
          Resource: ${self:provider.environment.SNS_TOPIC_ARN}
        - Effect: Allow
          Action: lex:*
          Resource: '*'
        - Effect: Allow
          Action:
            - lex:RecognizeText
            - lex:StartConversation
          Resource: "arn:aws:lex:us-east-1:433097106475:bot/UffsBot/alias/TelegramAlias/*"

functions:
  contactUsIntent:
    handler: handlers/contact_us.handle_contact_us_intent

  router:
    handler: router.handle_router

  telegramToLex:
    handler: middleware/telegramToLex.telegram_handler
    events:
      - http:
          path: telegram-webhook
          method: POST
          cors: true

plugins:
  - serverless-offline
  - serverless-python-requirements