const path = require("path");
require("dotenv").config({ path: path.resolve(__dirname, "../.env") });

class ExceptionMessagesConfig {
  constructor() {
    this.S3_DEFAULT_ERROR = process.env.S3_DEFAULT_ERROR;
    this.S3_BUCKET_NOT_FOUND_ERROR = process.env.S3_BUCKET_NOT_FOUND_ERROR;
    this.S3_ACCESS_DENIED_ERROR = process.env.S3_ACCESS_DENIED_ERROR;
    this.S3_KEY_NOT_FOUND_ERROR = process.env.S3_KEY_NOT_FOUND_ERROR;
    this.S3_KEY_ACCESS_DENIED_ERROR = process.env.S3_KEY_ACCESS_DENIED_ERROR;
    this.S3_FILE_NOT_FOUND_ERROR = process.env.S3_FILE_NOT_FOUND_ERROR;
    this.S3_FILE_ACCESS_DENIED_ERROR = process.env.S3_FILE_ACCESS_DENIED_ERROR;

    this.LEX_DEFAULT_ERROR = process.env.LEX_DEFAULT_ERROR;
    this.LEX_BOT_NOT_FOUND_ERROR = process.env.LEX_BOT_NOT_FOUND_ERROR;
    this.LEX_ACCESS_DENIED_ERROR = process.env.LEX_ACCESS_DENIED_ERROR;
    this.LEX_ALIAS_NOT_FOUND_ERROR = process.env.LEX_ALIAS_NOT_FOUND_ERROR;
    this.LEX_ALIAS_ACCESS_DENIED_ERROR =
      process.env.LEX_ALIAS_ACCESS_DENIED_ERROR;
    this.LEX_LOCALE_NOT_FOUND_ERROR = process.env.LEX_LOCALE_NOT_FOUND_ERROR;
    this.LEX_LOCALE_ACCESS_DENIED_ERROR =
      process.env.LEX_LOCALE_ACCESS_DENIED_ERROR;
    this.LEX_INTENT_NOT_FOUND_ERROR = process.env.LEX_INTENT_NOT_FOUND_ERROR;
    this.LEX_INTENT_ACCESS_DENIED_ERROR =
      process.env.LEX_INTENT_ACCESS_DENIED_ERROR;
    this.LEX_SLOT_NOT_FOUND_ERROR = process.env.LEX_SLOT_NOT_FOUND_ERROR;
    this.LEX_SLOT_ACCESS_DENIED_ERROR =
      process.env.LEX_SLOT_ACCESS_DENIED_ERROR;
    this.LEX_SESSION_NOT_FOUND_ERROR = process.env.LEX_SESSION_NOT_FOUND_ERROR;
    this.LEX_SESSION_ACCESS_DENIED_ERROR =
      process.env.LEX_SESSION_ACCESS_DENIED_ERROR;
    this.LEX_TEXT_NOT_FOUND_ERROR = process.env.LEX_TEXT_NOT_FOUND_ERROR;
    this.LEX_TEXT_ACCESS_DENIED_ERROR =
      process.env.LEX_TEXT_ACCESS_DENIED_ERROR;
    this.LEX_TRANSCRIPT_NOT_FOUND_ERROR =
      process.env.LEX_TRANSCRIPT_NOT_FOUND_ERROR;
    this.LEX_TRANSCRIPT_ACCESS_DENIED_ERROR =
      process.env.LEX_TRANSCRIPT_ACCESS_DENIED_ERROR;
    this.LEX_TRANSCRIPT_NOT_READY_ERROR =
      process.env.LEX_TRANSCRIPT_NOT_READY_ERROR;

    this.POLLY_DEFAULT_ERROR = process.env.POLLY_DEFAULT_ERROR;
    this.POLLY_ACCESS_DENIED_ERROR = process.env.POLLY_ACCESS_DENIED_ERROR;
    this.POLLY_VOICE_NOT_FOUND_ERROR = process.env.POLLY_VOICE_NOT_FOUND_ERROR;
    this.POLLY_VOICE_ACCESS_DENIED_ERROR =
      process.env.POLLY_VOICE_ACCESS_DENIED_ERROR;
    this.POLLY_TEXT_NOT_FOUND_ERROR = process.env.POLLY_TEXT_NOT_FOUND_ERROR;
    this.POLLY_TEXT_ACCESS_DENIED_ERROR =
      process.env.POLLY_TEXT_ACCESS_DENIED_ERROR;
    this.POLLY_OUTPUT_NOT_FOUND_ERROR =
      process.env.POLLY_OUTPUT_NOT_FOUND_ERROR;
    this.POLLY_OUTPUT_ACCESS_DENIED_ERROR =
      process.env.POLLY_OUTPUT_ACCESS_DENIED_ERROR;

    this.TRANSCRIBE_DEFAULT_ERROR = process.env.TRANSCRIBE_DEFAULT_ERROR;
    this.TRANSCRIBE_ACCESS_DENIED_ERROR =
      process.env.TRANSCRIBE_ACCESS_DENIED_ERROR;
    this.TRANSCRIBE_JOB_NOT_FOUND_ERROR =
      process.env.TRANSCRIBE_JOB_NOT_FOUND_ERROR;
    this.TRANSCRIBE_JOB_ACCESS_DENIED_ERROR =
      process.env.TRANSCRIBE_JOB_ACCESS_DENIED_ERROR;
    this.TRANSCRIBE_JOB_NOT_READY_ERROR =
      process.env.TRANSCRIBE_JOB_NOT_READY_ERROR;

    this.REKOGNITION_DEFAULT_ERROR = process.env.REKOGNITION_DEFAULT_ERROR;
    this.REKOGNITION_ACCESS_DENIED_ERROR =
      process.env.REKOGNITION_ACCESS_DENIED_ERROR;
    this.REKOGNITION_IMAGE_NOT_FOUND_ERROR =
      process.env.REKOGNITION_IMAGE_NOT_FOUND_ERROR;
    this.REKOGNITION_IMAGE_ACCESS_DENIED_ERROR =
      process.env.REKOGNITION_IMAGE_ACCESS_DENIED_ERROR;
    this.REKOGNITION_IMAGE_NOT_READY_ERROR =
      process.env.REKOGNITION_IMAGE_NOT_READY_ERROR;

    this.TWILIO_DEFAULT_ERROR = process.env.TWILIO_DEFAULT_ERROR;
    this.TWILIO_ACCESS_DENIED_ERROR = process.env.TWILIO_ACCESS_DENIED_ERROR;
    this.TWILIO_MESSAGE_NOT_FOUND_ERROR =
      process.env.TWILIO_MESSAGE_NOT_FOUND_ERROR;
    this.TWILIO_MESSAGE_ACCESS_DENIED_ERROR =
      process.env.TWILIO_MESSAGE_ACCESS_DENIED_ERROR;
    this.TWILIO_MESSAGE_NOT_READY_ERROR =
      process.env.TWILIO_MESSAGE_NOT_READY_ERROR;
  }
}

module.exports = new ExceptionMessagesConfig();
