service: final-lex-bot-v1
frameworkVersion: '3'

useDotenv: true

provider:
  name   : aws
  region : us-east-1 
  runtime: python3.9
  environment:
    API_KEY_OPENCAGE_GEOCODE: ${env:API_KEY_OPENCAGE_GEOCODE}


functions:
  lexIntentVerifier:
    handler: handler.handlerLexIntentVerifier
  cep_to_places:
    handler: controllers/intents/cep_to_places_controller.handle_cep_to_places

plugins:
  - serverless-offline
  - serverless-python-requirements